### ISSUE TITLE
Upload stac items into subfolder, not in the root of the storage blob

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-portal-frontend#12]
Items with non-unique names such as license.txt get overwritten every time you upload something to the storage blob. Either prepend some unique id to filenames (which might cause problems) or upload items into a subfolder structure.

The backend also might need editing, as the current endpoint for getting SAS tokens is get request.

**Comment by ivica3730k** [comment]
![scr1](https://github.com/SpatialDays/stac-portal-frontend/assets/17437897/c0e7048b-b450-4e2b-bf6f-655cc75740ff)
![scr2](https://github.com/SpatialDays/stac-portal-frontend/assets/17437897/2200c517-7861-45f7-98c0-263314f5e7de)

Or one could just escape the URL and put it in the get request (note the spaces in the endpoint once it is returned, no idea why is that there, probably backend problem)

**Comment by james-hinton** [comment]
fixed
