### ISSUE TITLE
bug: getting the user photo does not seem to work on staging

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-portal-frontend#32]
![image](https://github.com/SpatialDays/stac-portal-frontend/assets/17437897/cc6ab03d-f1b2-4fbd-9385-59e372d2ac29)
![image](https://github.com/SpatialDays/stac-portal-frontend/assets/17437897/f7c66880-cefe-4ab8-937a-d4feb905403c)

not sure how was it tested, but for some reason getting the user_claims object from /.auth/me does not work on staging

**Comment by mountaincharlie** [comment]
This should be work now as far as I can see, but i'll leave this open in case you notice anything wrong with it tomorrow

**Comment by ivica3730k** [comment]
Yup it does work. Will close
