### ISSUE TITLE
bug: auth does not work on staging

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-portal-frontend#33]
Just deployed the latest changes to prod. 

The auth is broken, console.log(userData) returns undefined and the header is not sent to the backend.

Was thinking only #32 is broken, but the whole auth procedure does not seem to work.

**Comment by ivica3730k** [comment]
Reverting the old auth back into the code seems to fix it, so it is something with the state management and getting the user photo it seems.

**Comment by ivica3730k** [comment]
I will leave that one back to you @mountaincharlie and @james-hinton . Once you are ready to deploy, just change the docker image in https://github.com/SpatialDays/EO_Infrastructure_Project_Terraform/blob/ae0ba64a17253ee50a7af742b687308b0b126a68/variables.tf#L46 and it will do it for you

**Comment by mountaincharlie** [comment]
I will have a look at that today
