### ISSUE TITLE
view stac button redirecting to wrong url

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-portal-frontend#96]
itemHref on this line is wrong

https://vscode.dev/github/SpatialDays/stac-portal-frontend/blob/staging/src/pages/Explorer/components/ToolboxItemsActions/ToolboxItemsActions.jsx#L129

we could just assemble the right URL from process.env.REACT_APP_PORTAL_API_MANAGEMENT_URL, collection_id and item_id.

then it will always be right, no matter from where the stac record comes.

p.s. I think the REACT_APP_PORTAL_API_MANAGEMENT_URL is set alright, as this 
https://vscode.dev/github/SpatialDays/stac-portal-frontend/blob/staging/src/pages/Explorer/components/ToolboxItems/ToolboxItems.jsx#L186

puts the header when the /search is done to APIM.

**Comment by james-hinton** [comment]
It was an API Management redirect issue
